In [2]:
import numpy as np
import matplotlib.pyplot as plt
# Constrants
N_STATES = 5  
N_ITERATIONS = 50 
TOLERANCE = 1e-5  


#Construct and normalize the transition matrix P, start by creating a random 5 by 5 matrix
P = np.random.rand(N_STATES, N_STATES)

# Normalize each row so it sums to 1, divide each row by the sum of that row
row_sums = P.sum(axis=1, keepdims=True)
P = P / row_sums

print("Transition Matrix P")
print(P)
print("\nRow sums of P:", P.sum(axis=1))


# Construct a random size-5 vector p and normalize it
p_initial = np.random.rand(N_STATES)
p_initial = p_initial / p_initial.sum()

print("Initial Probability Vector p (p_0)")
print(p_initial)
print(f"Initial sum: {p_initial.sum()}")

# Apply the transition rule 50 times, use p_new = P_transpose * p_old 
p_50 = p_initial.copy()
P_T = P.T  # Transpose of P

for _ in range(N_ITERATIONS):
    p_50 = np.dot(P_T, p_50)

print(f"Vector p after {N_ITERATIONS} iterations")
print(p_50)
print(f"Sum of p_50: {p_50.sum()}")


# Compute the stationary distribution (v)
print("Stationary Distribution (v)")
# Compute eigenvalues and eigenvectors of the transpose of P
eigenvalues, eigenvectors = np.linalg.eig(P_T)

# Find the index of the eigenvalue closest to 1 
eig_1_index = np.argmin(np.abs(eigenvalues - 1.0))
print(f"Eigenvalue closest to 1: {eigenvalues[eig_1_index]}")

# Get the corresponding eigenvector, and take the real part in case it is complex
v = eigenvectors[:, eig_1_index]
v = np.real(v)

# Scale the eigenvector so its components sum to 1
v = v / v.sum()

# Take the absolute value and normalize
v = np.abs(v)
v = v / v.sum()

print("Stationary Distribution v (scaled eigenvector)")
print(v)
print(f"Sum of v: {v.sum()}")

# Compare p_50 and the stationary distribution v by computing the componet-wise diffrence
difference = np.abs(p_50 - v)

# Check if all components match within the tolerance
matches = np.all(difference < TOLERANCE)

print(f"Comparison (Tolerance = {TOLERANCE})")
print(f"p_50 = {p_50}")
print(f"v    = {v}")
print(f"\nComponent-wise difference: {difference}")
print(f"\nDo p_50 and v match within {TOLERANCE}? {matches}")

Transition Matrix P
[[0.0562483  0.41069171 0.1061468  0.27535021 0.15156298]
 [0.22948014 0.40845284 0.14391732 0.05328438 0.16486532]
 [0.18132396 0.18834226 0.17443803 0.34941379 0.10648197]
 [0.2391243  0.0993583  0.38880327 0.15570891 0.11700523]
 [0.02259984 0.31503287 0.18667694 0.14655718 0.32913316]]

Row sums of P: [1. 1. 1. 1. 1.]
Initial Probability Vector p (p_0)
[0.21847443 0.28256024 0.30124295 0.19517216 0.00255023]
Initial sum: 1.0
Vector p after 50 iterations
[0.15895578 0.29390744 0.19548652 0.18092754 0.17072272]
Sum of p_50: 0.9999999999999998
Stationary Distribution (v)
Eigenvalue closest to 1: 0.9999999999999996
Stationary Distribution v (scaled eigenvector)
[0.15895578 0.29390744 0.19548652 0.18092754 0.17072272]
Sum of v: 1.0
Comparison (Tolerance = 1e-05)
p_50 = [0.15895578 0.29390744 0.19548652 0.18092754 0.17072272]
v    = [0.15895578 0.29390744 0.19548652 0.18092754 0.17072272]

Component-wise difference: [5.55111512e-17 0.00000000e+00 0.00000000e+00 1.9428